I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/park/park_endings.rpy", line 14, in script
    donoavan "Woah, Ethan...dude. NO!"
Exception: Sayer 'donoavan' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/park/park_endings.rpy", line 14, in script
    donoavan "Woah, Ethan...dude. NO!"
  File "C:\Users\Panko\Desktop\RenPy\renpy\ast.py", line 857, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Panko\Desktop\RenPy\renpy\ast.py", line 750, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'donoavan' is not defined.

Windows-10-10.0.22000
Ren'Py 8.0.0.22040201n
Visually Daunting 0.01
Tue Apr  5 01:13:23 2022
